apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: hello-v1-apisixroute
spec:
  http:
  - name: hello-v1
    match:
      hosts:
      - hello-v1-apisixroute.minikube.local
      paths:
      - /*
    backends:
    - serviceName: hello-v1-svc
      servicePort: 80
      weight: 80
    plugins:
      - name: ip-restriction
        enable: true
        config: 
          blacklist:
          - 10.244.0.1/32
          message: "Te bloquee individuo malo!!!!"